bgame/urls.py
from django.urls import path

from .views import IndexView, ListView, CreateView, UpdateView, DeleteView, signupfunc, loginfunc, logoutfunc, comment_create, wantplayfunc, interestfunc, detailfunc

app_name = 'bgame'

urlpatterns = [
    path('', IndexView.as_view(), name='welcome'),
    path('list/', ListView.as_view(), name='list'),
    path('<int:pk>', detailfunc, name='detail'),
    path('create/', CreateView.as_view(), name='create'),
    path('update/<int:pk>', UpdateView.as_view(), name='update'),
    path('delete/<int:pk>', DeleteView.as_view(), name='delete'),
    path('wantplay/<int:pk>', wantplayfunc, name='wantplay'),
    path('interest/<int:pk>', interestfunc, name='interest'),

    path('signup/', signupfunc, name='signup'),
    path('login/', loginfunc, name='login'),
    path('logout/', logoutfunc, name='logout'),

    #コメント作成
    path('comment/<int:pk>', comment_create, name='comment'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("bgame.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bgame/models.py
from django.db import models

from django.contrib.auth.models import User


WEIGHT = (
    ('軽量級', '軽量級'),
    ('中量級', '中量級'),
    ('重量級', '重量級'),
)



class Bgame(models.Model):
    title = models.CharField(verbose_name="タイトル", max_length=50)
    content = models.TextField(verbose_name="ゲーム概要")
    descrption = models.TextField(verbose_name="おすすめポイント", blank=True, default="")
    weight = models.CharField(verbose_name="重さ", max_length=50, choices=WEIGHT, null=True, blank=True)
    
    want_play = models.ManyToManyField(User, through="WantPlay", through_fields=("bgame", "user"), related_name="wantplays")
    interest = models.ManyToManyField(User, through="Interest", through_fields=("bgame", "user"), related_name="interests")

    image = models.ImageField(verbose_name="画像", blank=True, null=True, default=None)
    min_play = models.IntegerField(verbose_name="最低プレイ人数", default=2)

    class Meta:
        verbose_name = "ボードゲーム"
        verbose_name_plural = "ボードゲーム"

    def __str__(self):
        return self.title



class WantPlay(models.Model):
    bgame = models.ForeignKey(Bgame, models.CASCADE, related_name="wantplay_bgame")
    user = models.ForeignKey(User, models.CASCADE, related_name="wantplay_user")
    is_match = models.BooleanField(default=False)


    class Meta:
        verbose_name = "遊んでみたい"
        verbose_name_plural = "遊んでみたい"

    def __str__(self):
        return self.bgame.title



class Interest(models.Model):
    bgame = models.ForeignKey(Bgame, models.CASCADE, related_name="interest_bgame")
    user = models.ForeignKey(User, models.CASCADE, related_name="interest_user")


    class Meta:
        verbose_name = "興味あり"
        verbose_name_plural = "興味あり"

        constraints = [
            models.UniqueConstraint(
                fields=["bgame", "user"],
                name="interest_unique"
            ),
        ]

    def __str__(self):
        return self.bgame.title




class Comment(models.Model):
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    bgame = models.ForeignKey(Bgame, on_delete=models.CASCADE, default=None, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None, null=True)


    class Meta:
        verbose_name = "コメント"
        verbose_name_plural = "コメント"

    def __str__(self):
        return self.content

bgame/forms.py
from django import forms

from .models import Comment, WantPlay, Interest


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ("content", "bgame", "user")

        widgets = {
            "bgame": forms.HiddenInput(),
            "user": forms.HiddenInput()
        }

        labels = {
            "content": "コメントを入力"
        }




class WantPlayForm(forms.ModelForm):

    class Meta:
        model = WantPlay
        fields = ("user", "bgame")

        widgets = {
            "user": forms.HiddenInput(),
            "bgame": forms.HiddenInput()
        }




class InterestForm(forms.ModelForm):

    class Meta:
        model = Interest
        fields = ("user", "bgame")

        widgets = {
            "user": forms.HiddenInput(),
            "bgame": forms.HiddenInput()
        }

bgame/views.py
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.db import IntegrityError
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.core.mail import send_mail
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

from django.views.generic import TemplateView, ListView, UpdateView, CreateView, DeleteView

from .models import Bgame, Interest, WantPlay
from django.contrib.auth.models import User

from .forms import CommentForm, InterestForm, WantPlayForm


#アクセス制限用ミックスイン
class LoginRequiredMixin(LoginRequiredMixin):
    login_url = reverse_lazy('bgame:welcome')


#ウェルカムページ
class IndexView(TemplateView):
    template_name = 'bgame/welcome.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["top_object"] = Bgame.objects.order_by('?')[0]
        context["bgame_list"] = Bgame.objects.order_by('-title')[:3]

        return context



# 一覧表示
class ListView(LoginRequiredMixin, ListView):
    template_name = 'bgame/list.html'
    model = Bgame


    def get_queryset(self):
        qs = Bgame.objects.all()
        keyword = self.request.GET.get("q")

        if keyword:
            qs = qs.filter(title__contains=keyword)

        return qs



# 詳細表示
@login_required
def detailfunc(request, pk):
    bgame = Bgame.objects.get(pk=pk)

    wantplay_list = bgame.wantplay_bgame.filter(is_match=False)
    interest_list = bgame.interest_bgame.filter
    
    Wform = WantPlayForm() #遊びたいフォーム
    Iform = InterestForm() #興味ありフォーム
    Cform = CommentForm() #コメントフォーム
    
    return render(request, 'bgame/detail.html', {"object": bgame, "wantplay_list": wantplay_list, "interest_list": interest_list,\
                                                 "Wform": Wform, "Iform": Iform, "Cform": Cform})



# 作成機能
class CreateView(LoginRequiredMixin, CreateView):
    template_name = 'bgame/create.html'
    model = Bgame
    fields = ('title', 'content', 'descrption', 'weight', 'image', 'min_play')
    success_url = reverse_lazy("bgame:list")


# 更新機能
class UpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'bgame/update.html'
    model = Bgame
    fields = ('title', 'content', 'descrption', 'weight', 'image', 'min_play')

    def get_success_url(self):
        pk = self.kwargs.get("pk")
        return reverse("bgame:detail", kwargs={"pk": pk})

    def form_valid(self, form):
        messages.success(self.request, "更新しました")
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "更新できませんでした")
        return super().form_invalid(form)



# 削除機能
class DeleteView(LoginRequiredMixin, DeleteView):
    template_name = 'bgame/delete.html'
    model = Bgame
    success_url = reverse_lazy("bgame:list")

    def form_valid(self, form):
        messages.success(self.request, "削除しました")
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "削除できませんでした")
        return super().form_invalid(form)


# サインアップ
def signupfunc(request):
    if request.method == "POST":
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']

        try:
            User.objects.create_user(username, email, password)
            messages.success(request, "アカウントが正常に作成されました。")
            return redirect('bgame:welcome')
        except IntegrityError:
            messages.error(request, "このアカウント名は既に使用されています。")
            return render(request, 'bgame/signup.html')
    
    return render(request, 'bgame/signup.html')


# ログイン
def loginfunc(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            messages.success(request, "正常にログインしました。")
            return redirect('bgame:list')
        else:
            messages.error(request, "ログインできませんでした。ユーザー名かパスワードが間違っている可能性があります。")
            return redirect('bgame:welcome')


    return render(request, 'bgame/welcome.html')


# ログアウト
@login_required
def logoutfunc(request):
    logout(request)
    messages.success(request, "ログアウトしました。")
    return redirect('bgame:welcome')



# コメント作成
@login_required
def comment_create(request, pk):
    bgame = Bgame.objects.get(pk=pk)
    content = request.POST.get("content")
    user = request.user

    print(bgame)

    data = {"bgame": bgame, "content": content, "user": user}

    form = CommentForm(data=data)
    if form.is_valid():
        messages.success(request, "コメントを投稿しました。")
        form.save()

    return redirect("bgame:detail", pk=pk)



# 遊んでみたい機能
@login_required
def wantplayfunc(request, pk):
    bgame = Bgame.objects.get(pk=pk)
    user = request.user
        
    
    if not bgame.wantplay_bgame.filter(is_match=False, user=user):
        try:
            WantPlay.objects.create(bgame=bgame, user=user)
            messages.success(request, "このゲームにマッチング希望をしました。")
        except IntegrityError:
            pass
    else:
        messages.error(request, "既にマッチング希望をしています。")


    # マッチング処理
    match_list = bgame.wantplay_bgame.filter(is_match=False)
    print(match_list)
    if bgame.min_play == match_list.count():
        print("マッチング")
        for target in match_list:
            print("メール送信：" + str(target.user.email))
            send_mail(
            'マッチング通知',
            'おめでとうございます！\n遊びたい希望をしたゲームがマッチングしました！',
            'boardgate@example.com',
            [target.user.email]
            )
            target.is_match = True
            target.save()

    return redirect("bgame:detail", pk=pk)



# 興味あり機能
@login_required
def interestfunc(request, pk):
    bgame = Bgame.objects.get(pk=pk)
    user = request.user
    
    try:
        Interest.objects.create(bgame=bgame, user=user)
        messages.success(request, "このゲームに興味ありをしました。")
    except IntegrityError:
        messages.error(request, "既に興味ありをしています。")
        pass

    return redirect("bgame:detail", pk=pk)

templates/bgame/create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block content %}

<div class="text-center">
    <form method="post" enctype="multipart/form-data">{% csrf_token %}
        
        {{ form.title|as_crispy_field }}
        {{ form.content|as_crispy_field }}
        {{ form.descrption|as_crispy_field }}

        ゲームの重さ：{{ form.weight }}
        最小プレイ人数：{{ form.min_play }}
        <p class="mt-3">画像を選択：{{ form.image }}</p>

        <button class="btn btn-primary" type="submit">投稿</button>
    </form>
</div>

{% endblock content %}

templates/bgame/delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="my-5">
    <div class="row">
        <div class="col">
            <form method="post">{% csrf_token %}

                <h2>{{ object.title }}</h2>
                <div class="col-7">
                    {% if object.image %}
                        <img src="{{ object.image.url }}" width="300" class="img-fluid rounded border">
                    {% else %}
                        <img src="{% static 'images/noimage.png' %}" width="640" class="img-fluid rounded border">
                    {% endif %}
                </div>
                <p class="bg-danger text-white p-3">
                    本当に削除してもよろしいですか？
                </p>

                <button type="submit" class="btn btn-danger">削除</button>
                <a href="{% url 'bgame:detail' object.pk %}" class="btn btn-secondary">キャンセル</a>

            </form>
        </div>
    </div>
</div>

{% endblock content %}

templates/bgame/detail.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block content %}


<div class="row my-3">
    <div class="col-lg-12 text-center">
        <h1>{{ object.title }}</h1>
    </div>
    <div class="col-lg-7">
        {% if object.image %}
            <img src="{{ object.image.url }}" width="640" class="img-fluid rounded border">
        {% else %}
            <img src="{% static 'noimage.png' %}" width="640" class="img-fluid rounded border">
        {% endif %}
    </div>
    <div class="col-lg-5 bg-success">
        <h3><strong>ゲーム概要</strong></h3>
        <p>{{ object.content }}</p>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <h3>このボードゲームのおすすめポイント</h3>
        <p>{{ object.descrption }}</p>
    </div>
</div>
<hr>
<div class="row">
    <div class="col-3">
        <p class="text-muted">重さ：{{ object.weight }}</p>
    </div>
    <div class="col-7">
        <div class="alert alert-primary" role="alert">
            現在、{{ wantplay_list.count }}人の方がこのゲームを遊びたがっています！
        </div>
       
        <div class="alert alert-warning" role="alert">
            現在、{{ interest_list.count }}人の方がこのゲームに興味を持っています！
        </div>
    </div>

</div>

<hr>
<div class="row">
    <div class="col-lg-12">
        <a class="btn btn-info" href="{% url 'bgame:update' object.pk %}">編集</a>
        <a class="btn btn-danger" href="{% url 'bgame:delete' object.pk %}">削除</a>
        <p>
            <form action="{% url 'bgame:wantplay' object.pk %}">
                {{ Wform }}
                <button class="btn btn-outline-primary" type="submit">遊んでみたい！</button>
            </form>

            <form action="{% url 'bgame:interest' object.pk %}">
                {{ Iform }}
                <button class="btn btn-outline-warning" type="submit">興味あり！</button>
            </form>
        </p>
    </div>
</div>

<hr>
<!-- コメントエリア -->
<div class="row">
    <div class="col">
        <h3>-----コメント-----</h3>
        <ul class="list-unstyled">
            {% for comment in object.comment_set.all %}
                <li class="border-bottom mt-2">
                    ({{ comment.user }}さん): {{ comment.content }} -- ({{ comment.created }}
                </li>
            {% endfor %}
        </ul>
    </div>
</div>



<div class="row">
    <div class="col">
        <form method="POST" action="{% url 'bgame:comment' object.pk %}">{% csrf_token %}
            {{ Cform|crispy }}
            <button type="submit" class="btn btn-primary">送信</button>
        </form>
    </div>
</div>



{% endblock content %}

templates/bgame/list.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<div class="text-center mt-3">
    <h3>興味のあるボードゲームを探して、遊んでみたいボタンを押してみましょう！</h3>
</div>

<div class="accordion" id="collapse-accordion">
    <div class="card col-4">
      <div class="card-header" id="headingOne">
        <h5 class="mb-0">
          <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapse-accordion-1" aria-expanded="true" aria-controls="collapse-accordion-1">
            ゲームの重さとは？
          </button>
        </h5>
      </div>
  
      <div id="collapse-accordion-1" class="collapse" aria-labelledby="headingOne" data-parent="#collapse-accordion">
        <div class="card-body">
          重量とは、主にゲームのプレイ時間を表します。<br>
          目安としては、
          <strong>軽量級</strong>：15～30分
          <strong>中量級</strong>：30分～90分
          <strong>重量級</strong>：90分～
          となっています
        </div>
      </div>
    </div>
</div>

{% for item in object_list %}

<div class="media">
    {% if item.image %}
        <img src="{{ item.image.url }}"
            class="align-self-center mr-3" alt="..." width="120">
    {% else %}
        <img src="{% static 'noimage.png' %}"
            class="align-self-center mr-3" alt="..." width="120">
    {% endif %}
    <div class="media-body">
        <h5 class="mt-0"><a href="{% url 'bgame:detail' item.pk %}">{{ item.title }}</a></h5>
        <p class="mt-0">{{ item.content }}</p>
        <p class="mt-0">このゲームの重さ：{{ item.weight }}</p>
    </div>
</div>

{% if not forloop.last %}
    <hr>
{% endif %}

{% endfor %}

{% endblock content %}

templates/bgame/signup.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<div class="text-center">
    <h1>アカウント登録</h1>
    <p>{{ error }}</p>
</div>

<form action="" method="POST">{% csrf_token %}
    <div class="form-floating">
        <input type="text" class="form-control" id="floatingInput" placeholder="ユーザー名" name="username">
        <input type="email" class="form-control" id="floatingInput" placeholder="メールアドレス" name="email">
        <label for="email">マッチングメールを送信する際に使用します。</label>
        <input type="password" class="form-control" id="floatingPassword" placeholder="パスワード" name="password">
    </div>
<button class="w-100 btn btn-lg btn-primary" type="submit">登録する</button>
</form>

{% endblock content %}

templates/bgame/update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block content %}

<div class="text-center">
    <form method="post" enctype="multipart/form-data">{% csrf_token %}
        
        {{ form.title|as_crispy_field }}
        {{ form.content|as_crispy_field }}
        {{ form.descrption|as_crispy_field }}

        ゲームの重さ：{{ form.weight }}
        最小プレイ人数：{{ form.min_play }}
        <p class="mt-3">画像を選択：{{ form.image }}</p>

        <button class="btn btn-primary" type="submit">更新</button>
        <a class="btn btn-secondary" href="{% url 'bgame:detail' object.pk %}">戻る</a>
    </form>
</div>

{% endblock content %}

templates/bgame/welcome.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<!-- 画面上部 -->
<div class="row align-items-center my-5">
    <div class="col-lg-7">
        {% if top_object.image %}
            <img class="img-fluid rounded-circle mb-4 mb-lg-0" src="{{ top_object.image.url }}" alt="">
            <h2 class="text-center">{{ top_object.title }}</h2>
        {% else %}
            <img class="img-fluid rounded mb-4 mb-lg-0" src="{% static 'noimage.png' %}" alt="">
        {% endif %}
    </div>

    <div class="col-lg-5">
        <h1 class="font-weight-light">ようこそ<strong class="text-success">BoardGate</strong>へ！</h1>
        <form action="{% url 'bgame:login' %}" method="POST">{% csrf_token %}
            <input type="text" name="username" placeholder="ユーザー名"><br>
            <input type="password" name="password" placeholder="パスワード"><br>
            <button type="submit" class="btn btn-primary mt-2">ログイン</button>
        </form>
        
        <hr>
        <a class="btn btn-success mt-2" href="{% url 'bgame:signup' %}">アカウント登録</a>
        <p>アカウントをお持ちでない方はこちら</p>
        {% if message %}
        <p class="alert alert-secondary" role="alert">{{ message }}</p>
        {% endif %}
    </div>
</div>


<!-- 画面中部 -->
<div class="card text-white bg-secondary my-5 py-4 text-center">
    <div class="card-body">
      <p class="text-white m-0">現在こういったゲームが遊ばれています！</p>
    </div>
</div>

<!-- 画面下部 -->
<div class="row">

{% for item in bgame_list %}
<div class="col-md-4 mb-5">
    <div class="card h-100">
        {% if item.image %}
            <img class="card-img-top" src="{{ item.image.url }}" alt="{{ item.title }}"/>
        {% else %}
            <img class="card-img-top" src="{% static 'noimage.png' %}" alt="{{ item.title }}"/>
        {% endif %}
        <div class="card-body">
            <h2 class="card-title">{{ item.title }}</h2>
            <p class="card-text">{{ item.content }}</p>
        </div>
    </div>
</div>

{% endfor %}
</div>
<!-- /.row -->





{% endblock content %}