bgame/urls.py
from django.urls import path

from .views import IndexView, ListView, CreateView, UpdateView, DeleteView, signupfunc, loginfunc, logoutfunc, comment_create, wantplayfunc, interestfunc, detailfunc

app_name = 'bgame'

urlpatterns = [
    path('', IndexView.as_view(), name='welcome'),
    path('list/', ListView.as_view(), name='list'),
    path('<int:pk>', detailfunc, name='detail'),
    path('create/', CreateView.as_view(), name='create'),
    path('update/<int:pk>', UpdateView.as_view(), name='update'),
    path('delete/<int:pk>', DeleteView.as_view(), name='delete'),
    path('wantplay/<int:pk>', wantplayfunc, name='wantplay'),
    path('interest/<int:pk>', interestfunc, name='interest'),

    path('signup/', signupfunc, name='signup'),
    path('login/', loginfunc, name='login'),
    path('logout/', logoutfunc, name='logout'),

    #コメント作成
    path('comment/<int:pk>', comment_create, name='comment'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("bgame.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Custom styles for this template -->
  <link href="{% static 'css/small-business.css' %}" rel="stylesheet">

  <title>ボドゲート</title>
</head>


<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <a class="navbar-brand text-success">BoardGate -ボドゲート-</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" href="#">
            {% if request.user.is_authenticated %}
            ようこそ、{{ request.user.username }}さん
            {% else %}
            ログインしてください
            {% endif %}
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'bgame:list' %}">ボードゲーム一覧</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'bgame:create' %}">ボードゲームを投稿</a>
        </li>
      </ul>
      <form class="form-inline">
        <input class="form-control mr-sm-2" type="search" name="q" value="{{ request.GET.q }}" placeholder="ゲーム名を入力" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">検索</button>
      </form>
      
      <ul class="navbar-nav ml-auto ml-md-0">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="{% url 'bgame:list' %}">一覧ページ</a>
                <a class="nav-link" href="http://127.0.0.1:8000/admin">管理画面へ</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'bgame:logout' %}">ログアウト</a>
            </div>
        </li>
      </ul>
    </div>
  </div>
</nav>

{% if messages %}
  {% for message in messages %}
  <div {% if message.tags %} class="my-3 alert alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %} alert-dismissible fade show"{% endif %} role="alert">
    {{ message }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% endfor %}
{% endif %}


{% block content %}
{% endblock content %}


<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- fontawesome -->
<script src="https://kit.fontawesome.com/58838839f5.js" crossorigin="anonymous"></script>
</body>

</html>